# .sops.yaml
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - "age1022792u83cdvh97ffdq62826txxfsgpjpad7mvg92v2wsthuhumshjfu80" # Paste your converted age public key here
          - "age1q08etu0wn6zmtjxfk3ycl4675raa7c27vhya3qjm0fh7tm0gkc7sfru4cl"