# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c4b58b7c-a4c6-4b69-862f-2f642a2f7827";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f0ac1d29-a061-4a51-b854-2bb3c463b31d".device = "/dev/disk/by-uuid/f0ac1d29-a061-4a51-b854-2bb3c463b31d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D26E-2F4C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  #swapDevices =
 #   [ { device = "/dev/disk/by-uuid/dc5589bb-f492-4169-a6b6-b6534e766392"; }
#    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
